POST http://173.230.135.41:3001/api/users/registration
Content-Type: multipart/form-data
{
    "name": "Juan Prez",
    "email": "juan.perez@example.com",
    "password": "securepassword",
    "telefono": "123456789",
    "titulo": "Ingeniero de Software",
     "experiencia": "5 años",

}

GET http://173.230.135.41:3001/api/users



GET http://173.230.135.41:3001/api/users/getuser/5

GET http://173.230.135.41:3001/publicacion

